export type ToolCategory =
  | "AI / LLM Engineering"
  | "Automation / Orchestration"
  | "Data & Analytics"
  | "BI / Visualization"
  | "Engineering / DevOps"
  | "Knowledge Management / Second Brain"
  | "CRM / Job Search Operations"
  | "Communication / Notifications"
  | "Research / Intelligence"
  | "Testing / Validation";

export type ToolConfidence = "verified" | "likely" | "needs review";
export type ToolVisibility = "public" | "private-only" | "do-not-show";
export type ToolUsage =
  | "used in shipped projects"
  | "used in active workflows"
  | "used for learning / experimentation"
  | "mentioned in target workflows";

export interface ToolEntry {
  name: string;
  category: ToolCategory;
  evidenceSource: string;
  projects: string[];
  displayLabel: string;
  role: string;
  confidence: ToolConfidence;
  visibility: ToolVisibility;
  usage: ToolUsage;
}

export interface ToolLayer {
  label: string;
  heading: string;
  description: string;
  toolNames: string[];
}

export const toolInventory: ToolEntry[] = [
  {
    name: "Google Forms",
    category: "CRM / Job Search Operations",
    evidenceSource: "Portfolio flagship case study and resume page",
    projects: ["Job Application Automation"],
    displayLabel: "Forms",
    role: "manual intake for structured application records",
    confidence: "verified",
    visibility: "public",
    usage: "used in active workflows",
  },
  {
    name: "Gmail",
    category: "CRM / Job Search Operations",
    evidenceSource: "Portfolio flagship case study and resume page",
    projects: ["Job Application Automation"],
    displayLabel: "Gmail",
    role: "confirmation, recruiter, interview, and follow-up signal source",
    confidence: "verified",
    visibility: "public",
    usage: "used in active workflows",
  },
  {
    name: "Google Calendar",
    category: "CRM / Job Search Operations",
    evidenceSource: "Portfolio flagship case study, Canvas agent README, and resume page",
    projects: ["Job Application Automation", "Canvas Assignment Calendar Agent"],
    displayLabel: "Calendar",
    role: "follow-up reminders, interview prep blocks, and assignment reminders",
    confidence: "verified",
    visibility: "public",
    usage: "used in shipped projects",
  },
  {
    name: "Google Sheets",
    category: "CRM / Job Search Operations",
    evidenceSource: "Portfolio flagship case study and resume page",
    projects: ["Job Application Automation"],
    displayLabel: "Sheets",
    role: "master tracker, schemas, and reporting tables",
    confidence: "verified",
    visibility: "public",
    usage: "used in active workflows",
  },
  {
    name: "Obsidian",
    category: "Knowledge Management / Second Brain",
    evidenceSource: "Resume highlights and local AI Second Brain vault inventory",
    projects: ["AI Second Brain workflows"],
    displayLabel: "Obsidian",
    role: "project memory, note capture, and operating-system documentation",
    confidence: "verified",
    visibility: "public",
    usage: "used in active workflows",
  },
  {
    name: "Markdown",
    category: "Knowledge Management / Second Brain",
    evidenceSource: "Portfolio repo, project READMEs, and resume page",
    projects: ["Portfolio", "GitHub project docs", "AI Second Brain workflows"],
    displayLabel: "Markdown",
    role: "READMEs, validation notes, briefs, and reusable documentation",
    confidence: "verified",
    visibility: "public",
    usage: "used in shipped projects",
  },
  {
    name: "Claude",
    category: "AI / LLM Engineering",
    evidenceSource: "Portfolio flagship case study and resume page",
    projects: ["Job Application Automation", "AI Second Brain workflows"],
    displayLabel: "Claude",
    role: "reasoning, writing, fit scoring, and review loops",
    confidence: "verified",
    visibility: "public",
    usage: "used in active workflows",
  },
  {
    name: "OpenAI GPT-4o",
    category: "AI / LLM Engineering",
    evidenceSource: "Portfolio flagship case study and resume page",
    projects: ["Job Application Automation"],
    displayLabel: "GPT-4o",
    role: "structured extraction and JSON normalization",
    confidence: "verified",
    visibility: "public",
    usage: "used in active workflows",
  },
  {
    name: "Anthropic Console",
    category: "AI / LLM Engineering",
    evidenceSource: "Resume page and resume highlights",
    projects: ["AI workflow practice"],
    displayLabel: "Anthropic Console",
    role: "prompt testing and model-behavior checks",
    confidence: "verified",
    visibility: "public",
    usage: "used for learning / experimentation",
  },
  {
    name: "Claude Code",
    category: "AI / LLM Engineering",
    evidenceSource: "Local AI Second Brain command-center indexes and transcript inventory",
    projects: ["Portfolio implementation", "AI Second Brain workflows"],
    displayLabel: "Claude Code",
    role: "repo-aware implementation sessions and agentic coding workflows",
    confidence: "verified",
    visibility: "public",
    usage: "used in active workflows",
  },
  {
    name: "Codex",
    category: "AI / LLM Engineering",
    evidenceSource: "Local AI Second Brain command-center indexes and current portfolio workflow",
    projects: ["Portfolio implementation", "AI Second Brain workflows"],
    displayLabel: "Codex",
    role: "terminal-based repo work, verification, and implementation support",
    confidence: "verified",
    visibility: "public",
    usage: "used in active workflows",
  },
  {
    name: "ChatGPT",
    category: "AI / LLM Engineering",
    evidenceSource: "Local AI Second Brain export inventory",
    projects: ["AI Second Brain workflows"],
    displayLabel: "ChatGPT",
    role: "conversation archive and research synthesis input",
    confidence: "verified",
    visibility: "public",
    usage: "used in active workflows",
  },
  {
    name: "Cursor",
    category: "AI / LLM Engineering",
    evidenceSource: "Resume page and resume highlights",
    projects: ["AI-assisted development workflows"],
    displayLabel: "Cursor",
    role: "AI-assisted code editing and local development",
    confidence: "verified",
    visibility: "public",
    usage: "used for learning / experimentation",
  },
  {
    name: "Zapier",
    category: "Automation / Orchestration",
    evidenceSource: "Portfolio flagship case study and resume page",
    projects: ["Job Application Automation"],
    displayLabel: "Zapier",
    role: "event-driven automation across form, email, sheet, and calendar steps",
    confidence: "verified",
    visibility: "public",
    usage: "used in active workflows",
  },
  {
    name: "n8n",
    category: "Automation / Orchestration",
    evidenceSource: "Resume page and resume highlights",
    projects: ["AI automation practice"],
    displayLabel: "n8n",
    role: "workflow orchestration practice and automation prototyping",
    confidence: "verified",
    visibility: "public",
    usage: "used for learning / experimentation",
  },
  {
    name: "Google Apps Script",
    category: "Automation / Orchestration",
    evidenceSource: "Portfolio flagship case study and resume page",
    projects: ["Job Application Automation"],
    displayLabel: "Apps Script",
    role: "spreadsheet automation and utility scripts",
    confidence: "verified",
    visibility: "public",
    usage: "used in active workflows",
  },
  {
    name: "GitHub Actions",
    category: "Automation / Orchestration",
    evidenceSource: "Portfolio README and Spotify Analytics README",
    projects: ["Portfolio", "Spotify Analytics"],
    displayLabel: "GitHub Actions",
    role: "CI, Pages deployment, and demo-media refresh workflows",
    confidence: "verified",
    visibility: "public",
    usage: "used in shipped projects",
  },
  {
    name: "Slack",
    category: "Communication / Notifications",
    evidenceSource: "Portfolio Currently Building strip",
    projects: ["Job Application Automation v2"],
    displayLabel: "Slack",
    role: "planned notifications for the active job-search automation workflow",
    confidence: "verified",
    visibility: "public",
    usage: "mentioned in target workflows",
  },
  {
    name: "Python",
    category: "Data & Analytics",
    evidenceSource: "Linked GitHub READMEs and resume page",
    projects: ["Decision Intelligence Lab", "Spotify Analytics", "SEC Pipeline", "Canvas Agent"],
    displayLabel: "Python",
    role: "ETL, API clients, analytics engines, and automation scripts",
    confidence: "verified",
    visibility: "public",
    usage: "used in shipped projects",
  },
  {
    name: "pandas",
    category: "Data & Analytics",
    evidenceSource: "Decision Intelligence Lab README, Spotify README, and resume page",
    projects: ["Decision Intelligence Lab", "Spotify Analytics", "Sales Data Cleaning"],
    displayLabel: "pandas",
    role: "data cleaning, transformations, and analytical datasets",
    confidence: "verified",
    visibility: "public",
    usage: "used in shipped projects",
  },
  {
    name: "SQL",
    category: "Data & Analytics",
    evidenceSource: "SQL project READMEs and resume page",
    projects: ["SQL Retail Revenue Analysis", "SQL Labor Market Intelligence", "Airbnb Market Intelligence"],
    displayLabel: "SQL",
    role: "relational modeling, views, quality checks, and analysis queries",
    confidence: "verified",
    visibility: "public",
    usage: "used in shipped projects",
  },
  {
    name: "SQLite",
    category: "Data & Analytics",
    evidenceSource: "Linked GitHub READMEs and resume page",
    projects: ["Decision Intelligence Lab", "Spotify Analytics", "SEC Pipeline", "SQL projects"],
    displayLabel: "SQLite",
    role: "local analytical stores and reproducible query layers",
    confidence: "verified",
    visibility: "public",
    usage: "used in shipped projects",
  },
  {
    name: "R",
    category: "Data & Analytics",
    evidenceSource: "Resume page and resume highlights",
    projects: ["Coursework and analytics practice"],
    displayLabel: "R",
    role: "analytics coursework and statistical practice",
    confidence: "verified",
    visibility: "public",
    usage: "used for learning / experimentation",
  },
  {
    name: "Excel",
    category: "Data & Analytics",
    evidenceSource: "Resume page and resume highlights",
    projects: ["Analytics coursework and business review workflows"],
    displayLabel: "Excel",
    role: "spreadsheet analysis and business review workflows",
    confidence: "verified",
    visibility: "public",
    usage: "used in active workflows",
  },
  {
    name: "SEC EDGAR",
    category: "Research / Intelligence",
    evidenceSource: "SEC Financial Statement Pipeline README and resume page",
    projects: ["SEC Financial Statement Pipeline"],
    displayLabel: "SEC EDGAR",
    role: "official source data for financial-statement ETL",
    confidence: "verified",
    visibility: "public",
    usage: "used in shipped projects",
  },
  {
    name: "Spotify/Spotipy",
    category: "Research / Intelligence",
    evidenceSource: "Spotify Analytics README",
    projects: ["Spotify Analytics"],
    displayLabel: "Spotify API",
    role: "OAuth-backed music-data collection and playlist analysis",
    confidence: "verified",
    visibility: "public",
    usage: "used in shipped projects",
  },
  {
    name: "Canvas",
    category: "Research / Intelligence",
    evidenceSource: "Canvas Assignment Calendar Agent README",
    projects: ["Canvas Assignment Calendar Agent"],
    displayLabel: "Canvas API",
    role: "assignment-state source for calendar automation",
    confidence: "verified",
    visibility: "public",
    usage: "used in shipped projects",
  },
  {
    name: "Tableau",
    category: "BI / Visualization",
    evidenceSource: "Tableau Forecasting README, dashboard export, and resume page",
    projects: ["Tableau Forecasting & Discount Analysis", "Airbnb Market Intelligence"],
    displayLabel: "Tableau",
    role: "executive dashboards and forecasting studies",
    confidence: "verified",
    visibility: "public",
    usage: "used in shipped projects",
  },
  {
    name: "Power BI",
    category: "BI / Visualization",
    evidenceSource: "Resume page and resume highlights",
    projects: ["BI practice"],
    displayLabel: "Power BI",
    role: "BI reporting and dashboard practice",
    confidence: "verified",
    visibility: "public",
    usage: "used for learning / experimentation",
  },
  {
    name: "Streamlit",
    category: "BI / Visualization",
    evidenceSource: "Decision Intelligence, Spotify, and Airbnb READMEs",
    projects: ["Decision Intelligence Lab", "Spotify Analytics", "Airbnb Market Intelligence"],
    displayLabel: "Streamlit",
    role: "interactive analytics applications",
    confidence: "verified",
    visibility: "public",
    usage: "used in shipped projects",
  },
  {
    name: "Plotly",
    category: "BI / Visualization",
    evidenceSource: "Decision Intelligence, Spotify, and Airbnb READMEs",
    projects: ["Decision Intelligence Lab", "Spotify Analytics", "Airbnb Market Intelligence"],
    displayLabel: "Plotly",
    role: "charts, KPI views, and exploratory interfaces",
    confidence: "verified",
    visibility: "public",
    usage: "used in shipped projects",
  },
  {
    name: "GitHub",
    category: "Engineering / DevOps",
    evidenceSource: "Portfolio, linked project repos, and resume page",
    projects: ["Portfolio", "All linked GitHub project repos"],
    displayLabel: "GitHub",
    role: "source control, project proof, and documentation surface",
    confidence: "verified",
    visibility: "public",
    usage: "used in shipped projects",
  },
  {
    name: "VS Code",
    category: "Engineering / DevOps",
    evidenceSource: "Resume page and local workflow setup evidence",
    projects: ["Portfolio implementation", "AI Second Brain workflows"],
    displayLabel: "VS Code",
    role: "local development and integrated terminal workflows",
    confidence: "verified",
    visibility: "public",
    usage: "used in active workflows",
  },
  {
    name: "PowerShell",
    category: "Engineering / DevOps",
    evidenceSource: "Resume page and local workflow setup evidence",
    projects: ["Portfolio implementation", "Windows automation workflows"],
    displayLabel: "PowerShell",
    role: "Windows automation, validation, and command execution",
    confidence: "verified",
    visibility: "public",
    usage: "used in active workflows",
  },
  {
    name: "pytest",
    category: "Testing / Validation",
    evidenceSource: "Decision Intelligence Lab README and resume page",
    projects: ["Decision Intelligence Lab"],
    displayLabel: "pytest",
    role: "Python regression coverage for analytics logic",
    confidence: "verified",
    visibility: "public",
    usage: "used in shipped projects",
  },
  {
    name: "unittest",
    category: "Testing / Validation",
    evidenceSource: "Spotify README, Canvas README, and resume page",
    projects: ["Spotify Analytics", "Canvas Assignment Calendar Agent", "Job Market Skill Radar"],
    displayLabel: "unittest",
    role: "stdlib test coverage for automation and private workflow pilots",
    confidence: "verified",
    visibility: "public",
    usage: "used in shipped projects",
  },
  {
    name: "Glean",
    category: "Knowledge Management / Second Brain",
    evidenceSource: "Resume highlights and existing workflow stack",
    projects: ["Knowledge workflows"],
    displayLabel: "Glean",
    role: "knowledge retrieval across work materials",
    confidence: "verified",
    visibility: "public",
    usage: "used in active workflows",
  },
  {
    name: "Gemini CLI",
    category: "AI / LLM Engineering",
    evidenceSource: "No supporting public repo, resume, or safe local evidence found",
    projects: [],
    displayLabel: "Gemini CLI",
    role: "not rendered",
    confidence: "needs review",
    visibility: "do-not-show",
    usage: "mentioned in target workflows",
  },
  {
    name: "Notion",
    category: "Knowledge Management / Second Brain",
    evidenceSource: "No supporting public repo, resume, or safe local evidence found",
    projects: [],
    displayLabel: "Notion",
    role: "not rendered",
    confidence: "needs review",
    visibility: "do-not-show",
    usage: "mentioned in target workflows",
  },
  {
    name: "Figma",
    category: "Engineering / DevOps",
    evidenceSource: "No supporting public repo, resume, or safe local evidence found",
    projects: [],
    displayLabel: "Figma",
    role: "not rendered",
    confidence: "needs review",
    visibility: "do-not-show",
    usage: "mentioned in target workflows",
  },
  {
    name: "Miro",
    category: "Engineering / DevOps",
    evidenceSource: "No supporting public repo, resume, or safe local evidence found",
    projects: [],
    displayLabel: "Miro",
    role: "not rendered",
    confidence: "needs review",
    visibility: "do-not-show",
    usage: "mentioned in target workflows",
  },
  {
    name: "Jira",
    category: "Engineering / DevOps",
    evidenceSource: "No supporting public repo, resume, or safe local evidence found",
    projects: [],
    displayLabel: "Jira",
    role: "not rendered",
    confidence: "needs review",
    visibility: "do-not-show",
    usage: "mentioned in target workflows",
  },
  {
    name: "HubSpot",
    category: "CRM / Job Search Operations",
    evidenceSource: "No supporting public repo, resume, or safe local evidence found",
    projects: [],
    displayLabel: "HubSpot",
    role: "not rendered",
    confidence: "needs review",
    visibility: "do-not-show",
    usage: "mentioned in target workflows",
  },
  {
    name: "Recruiter CRM tools",
    category: "CRM / Job Search Operations",
    evidenceSource: "Current public evidence is generic and not product-specific",
    projects: ["Job Application Automation v2"],
    displayLabel: "Recruiter CRM",
    role: "not rendered until the specific public-safe system is documented",
    confidence: "needs review",
    visibility: "do-not-show",
    usage: "mentioned in target workflows",
  },
];

export const toolLayers: ToolLayer[] = [
  {
    label: "Capture",
    heading: "Inputs and operating signals",
    description: "Application records, email signals, calendar timing, source APIs, and project notes.",
    toolNames: [
      "Google Forms",
      "Gmail",
      "Google Calendar",
      "Google Sheets",
      "Canvas",
      "Spotify/Spotipy",
      "SEC EDGAR",
    ],
  },
  {
    label: "Command center",
    heading: "Project memory and coordination",
    description: "The documentation layer that keeps assumptions, decisions, and proof artifacts traceable.",
    toolNames: ["Obsidian", "Markdown", "Glean", "GitHub", "VS Code", "PowerShell"],
  },
  {
    label: "AI / reasoning",
    heading: "Assisted engineering and model workflows",
    description: "Models and agent tools used for extraction, reasoning, implementation, and review.",
    toolNames: [
      "Claude",
      "OpenAI GPT-4o",
      "Anthropic Console",
      "Claude Code",
      "Codex",
      "ChatGPT",
      "Cursor",
    ],
  },
  {
    label: "Data / analysis",
    heading: "Analytics engines and storage",
    description: "Data cleaning, query layers, local stores, and analysis code behind the portfolio work.",
    toolNames: ["Python", "pandas", "SQL", "SQLite", "R", "Excel"],
  },
  {
    label: "Visualization / apps",
    heading: "Reviewable surfaces",
    description: "Dashboards and interfaces that make the work inspectable by a hiring manager.",
    toolNames: ["Tableau", "Power BI", "Streamlit", "Plotly"],
  },
  {
    label: "Automation / validation",
    heading: "Delivery, tests, and evidence loops",
    description: "Automation runners and test layers that keep workflows repeatable.",
    toolNames: [
      "Zapier",
      "n8n",
      "Google Apps Script",
      "GitHub Actions",
      "Slack",
      "pytest",
      "unittest",
    ],
  },
];

export const publicVerifiedTools = toolInventory.filter(
  (tool) => tool.visibility === "public" && tool.confidence === "verified",
);

export function getVisibleTools(toolNames: string[]): ToolEntry[] {
  return toolNames
    .map((name) => publicVerifiedTools.find((tool) => tool.name === name))
    .filter((tool): tool is ToolEntry => Boolean(tool));
}
